# -*- coding: utf-8 -*-
"""
Arquivo de linguagem para o Total Battle Tools
Contém todas as strings traduzidas usadas na aplicação
"""

# Dicionário de idiomas disponíveis
LANGUAGES = {
    "pt": "Português",
    "en": "English"
}

# Interface principal
UI = {
    "pt": {
        "main_title": "Seletor de Criptas",
        "btn_common": "Comum",
        "btn_epic": "Épica",
        "btn_rare": "Rara",
        "btn_any": "Any",
        "any_mode_active": "Modo 'Any' ativo: Ataca qualquer cripta.",
        "btn_calibrate": "Calibrar",
        "btn_select_all": "Selecionar Tudo",
        "btn_play": "Iniciar",
        "lbl_crypt_qty": "Qtd Criptas:",
        "status_title": "Status - Cripting",
        "language": "Idioma:",
        "info_title": "Informação",
        "no_images_found": "Nenhuma imagem encontrada em {}",
        "calibration_script_not_found_msg": "Script de calibração não encontrado:\n{}",
        "warning_title": "Aviso",
        "calibration_title": "Calibração",
        "start_button": "Iniciar",
        "warning_title": "Aviso",
        "calibration_script_error": "Erro ao executar o script de calibração:\n{}",
        "script_already_running": "O script já está em execução.",
        "no_images_selected": "Nenhuma imagem selecionada!",
        "calibration_title": "Calibração",
        "position_captured": "Posição de {} capturada com sucesso!",
        "position_captured_finished": "Posição de {} capturada com sucesso! Finalizado. Todos os parâmetros foram capturados.",
        "enter_crypt_quantity": "Informe a quantidade de criptas!",
        "error_title": "Erro",
        "scroll_capture_title": "Captura de Rolagem",
        "scroll_capture_msg": "Role o mouse para capturar a quantidade de rolagem. Clique com o botão esquerdo para finalizar.",
        "config_file_not_found": "Arquivo de configuração não encontrado: {}",
        "coordinates_section_not_found": "Seção [COORDINATES] não encontrada no arquivo de configuração.",
        "save_config_fail": "Falha ao salvar configuração: {}",
        "mouse_selection_title": "Seleção do Mouse",
        "ok_button": "OK",
        "developed_by": "Desenvolvido por:",
        "calibration_success": "Posição de {} capturada com sucesso!",
        "calibration_finished": "Posição de {} capturada com sucesso! Finalizado. Todos os parâmetros foram capturados.",
        "game_window_not_found": "Não foi possível encontrar ou ativar a janela '{}'.\nVerifique se o jogo está aberto e o título está correto."
    },
    "en": {
        "main_title": "Crypt Selector",
        "btn_common": "Common",
        "btn_epic": "Epic",
        "btn_rare": "Rare",
        "btn_any": "Any",
        "any_mode_active": "'Any' mode active: any crypt will be attacked.",
        "btn_calibrate": "Calibrate",
        "btn_select_all": "Select All",
        "btn_play": "Start",
        "lbl_crypt_qty": "Crypt Qty:",
        "status_title": "Status - Cripting",
        "language": "Language:",
        "info_title": "Information",
        "mouse_selection_title": "Mouse Selection",
        "ok_button": "OK",
        "developed_by": "Developed by:",
        "calibration_title": "Calibration",
        "start_button": "Start",
        "warning_title": "Warning",
        "scroll_capture_title": "Scroll Capture",
        "scroll_capture_msg": "Scroll the mouse to capture the scroll amount. Left click to finish.",
        "calibration_success": "{} position captured successfully!",
        "calibration_finished": "{} position captured successfully! Finished. All parameters have been captured.",
        "no_images_found": "No images found in {}",
        "calibration_title": "Calibration",
        "position_captured": "{} position captured successfully!",
        "position_captured_finished": "{} position captured successfully! Finished. All parameters have been captured.",
        "config_error_title": "Configuration Error",
        "config_read_write_error": "Error reading or writing configuration file:\n{}",
        "error_title": "Error",
        "unexpected_error": "An unexpected error occurred:\n{}",
        "config_file_not_found": "Configuration file not found: {}",
        "coordinates_section_not_found": "[COORDINATES] section not found in configuration file.",
        "save_config_fail": "Failed to save configuration: {}",
        "warning_title": "Warning",
        "game_window_not_found": "Could not find or activate the '{}' window.\nPlease check if the game is open and the title is correct.",
        "enter_crypt_quantity": "Please enter the crypt quantity!",
        "calibration_script_error": "Error executing calibration script:\n{}",
        "script_already_running": "The script is already running.",
        "no_images_selected": "No images selected!",
        "calibration_script_not_found_msg": "Calibration script not found:\n{}"
    }
}

# Mensagens de alerta e erro
MESSAGES = {
    "pt": {
        "warning": "Aviso",
        "error": "Erro",
        "success": "Sucesso",
        "info": "Informação",
        "script_running": "O script já está em execução.",
        "no_images": "Nenhuma imagem selecionada!",
        "enter_qty": "Informe a quantidade de criptas!",
        "calibration_instructions": "Abra o Total Battle e configure as criptas para aparecer apenas as criptas raras no nível que quiser. Tenha certeza que você tenha pelo menos uma chave para a cripta rara.",
        "config_saved": "Configuração salva. Quantidade de criptas: {}",
        "config_save_error": "Falha ao salvar configuração: {}",
        "click_watchtower_icon": "Clique no icone da luneta para abrir o menu",
        "click_cripts_menu": "Clique no menu criptas e arenas",
        "select_cript_icon_area": "Selecione a área do icone da cripta na lista de criptas, não clicar no icone e sim selecionar a área do icone",
        "select_go_button_area": "Selecione a área do botão go corresponde a mesma cripta selecionada anteriormente, não clicar no botão GO e sim selecionar a área do botão",
        "click_cript_on_map": "Clique na cripta",
        "click_open_button": "Clique no botão open",
        "select_explorer_button_area": "Selecione a área do botão explorer, não clicar no botão e sim selecionar a área",
        "click_speedup_button": "Clique no botão speed up",
        "select_speedup_icon_area": "Selecione a área do icone do speedup (os 3 soldados marchando)",
        "click_use_button": "Por ultimo clique no botão use",
        "window_not_found": "Não foi possível encontrar ou ativar a janela '{}'.\nVerifique se o jogo está aberto e o título está correto.",
        "config_file_not_found": "Arquivo de configuração não encontrado: {}",
        "section_not_found": "Seção [COORDINATES] não encontrada no arquivo de configuração.",
        "no_images_in_dir": "Nenhuma imagem encontrada em {}"
    },
    "en": {
        "warning": "Warning",
        "error": "Error",
        "success": "Success",
        "info": "Information",
        "calibration_instructions": "Open Total Battle and configure the crypts to show only rare crypts at the level you want. Make sure you have at least one key for the rare crypt.",
        "script_running": "The script is already running.",
        "no_images": "No images selected!",
        "enter_qty": "Please enter the number of crypts!",
        "click_watchtower_icon": "Click on the spyglass icon to open the menu",
        "click_cripts_menu": "Click on the crypts and arenas menu",
        "select_cript_icon_area": "Select the area of the crypt icon in the crypt list, don't click on the icon but select the icon area",
        "select_go_button_area": "Select the area of the GO button corresponding to the same crypt selected earlier, don't click on the GO button but select the button area",
        "click_cript_on_map": "Click on the crypt",
        "click_open_button": "Click on the open button",
        "select_explorer_button_area": "Select the area of the explorer button, don't click on the button but select the area",
        "click_speedup_button": "Click on the speed up button",
        "select_speedup_icon_area": "Select the area of the speedup icon (the 3 marching soldiers)",
        "click_use_button": "Finally click on the use button",
        "config_saved": "Configuration saved. Number of crypts: {}",
        "config_save_error": "Failed to save configuration: {}",
        "window_not_found": "Could not find or activate the '{}' window.\nMake sure the game is open and the title is correct.",
        "config_file_not_found": "Configuration file not found: {}",
        "section_not_found": "Section [COORDINATES] not found in the configuration file.",
        "no_images_in_dir": "No images found in {}"
    }
}

# Mensagens de log
LOGS = {
    "pt": {
        "closing_main": "Fechando janela principal...",
        "terminating_process": "Terminando processo cripting...",
        "child_process_terminated": "Processo filho terminado.",
        "child_process_error": "Erro ao terminar processo filho: {}",
        "destroying_status": "Destruindo janela de status...",
        "destroying_main": "Destruindo janela principal...",
        "exiting_script": "Saindo do script launcher...",
        "closing_status": "Fechando janela de status...",
        "window_not_found": "Janela '{}' não encontrada.",
        "window_size_error": "Erro ao capturar tamanho da janela: {}",
        "trying_terminate_process": "Tentando terminar processo cripting...",
        "sending_kill": "Enviando kill() para o processo...",
        "process_terminated": "Processo terminado via kill() e wait().",
        "process_timeout": "Processo não terminou após kill() e wait() (TimeoutExpired). Isso é inesperado.",
        "kill_error": "Erro ao tentar matar o processo: {}",
        "process_ref_cleared": "Referência do processo limpa.",
        "status_update_error": "Não foi possível atualizar a janela de status (provavelmente já destruída).",
        "destroying_status_window": "Destruindo a janela de status.",
        "status_close_complete": "Fechamento da janela de status concluído.",
        "config_saved_debug": "Salvando no config: search_cript = {}",
        "activating_window": "Tentando ativar a janela: {}",
        "starting_script": "Iniciando script...\n",
        "dir_not_found": "Aviso: Diretório não encontrado: {}",
        "rel_path_error": "Erro ao gerar caminho relativo para: {}",
        "selected_items": "Selecionados: {}",
        "cripta_encontrada": "Cripta encontrada",
        "window_found": "Janela '{}' encontrada (HWND: {}).",
        "window_maximizing": "Maximizando a janela '{}'...",
        "window_activating_wscript": "Tentando ativar a janela '{}' via WScript.Shell...",
        "window_minimized": "Janela '{}' está minimizada. Restaurando...",
        "wrong_windows_opened": "Havia janelas erradas abertas",
        "explore_button_not_found": "Botão Explorar não encontrado, tente outra posição",
        "explorer_button_after_store_not_found": "Botão Explorer após tela da loja não encontrado, procurando próximo ponto de clique",
        "config_load_error": "Erro ao carregar configuração inicial: {}",
        "script_finished": "--- Script Finalizado ---",
        "selected_paths": "Selecionados:",
        "error_in_speedy_march": "Erro ao acelerar a marcha",
        "process_killed": "Processo terminado via kill() e wait().",
        "process_not_killed_timeout": "Processo não terminou após kill() e wait() (TimeoutExpired). Isso é inesperado.",
        "error_killing_process": "Erro ao tentar matar o processo: {}",
        "troops_screen_close": "Tela de tropas fechada",
        "process_interrupted_by_user": "--- Processo Interrompido pelo Usuário ---",
        "waiting_acceleration_screen_close": "Agaurdando fechamento da tela de aceleração",
        "esc_pressed_interrupting": "Tecla Esc pressionada. Interrompendo...",
        "time_is_over": "O tempo acabou!",
        "Invading_crypt": "Invadindo a cripta",
        "cript_speedup": "Acelerando a marcha",
        "explored_cripts": "Criptas exploradas",
        "error_in_speedup_march": "Erro ao acelerar a marcha",
        "error_in_cript": "Erro na cripta",
        "activating_window": "Tentando ativar a janela: {}",
        "error_serch_cript": "Erro na busca da cripta",
        "store_screen_close": "Tela da loja fechada",
        "trying_activate_window": "Tentando ativar a janela: {}",
        "cripting_interrupted": "Invasão da cripta interrompida",
        "no_directory_loaded": "Nenhum diretório carregado para selecionar tudo.",
        "image_load_error": "Erro ao carregar imagem {}: {}",
        "selecting_all_in": "Selecionando tudo em: {}",
        "window_activated": "Janela '{}' ativada com sucesso.",
        "setforeground_failed": "SetForegroundWindow também falhou.",
        "setforeground_error": "Erro ao usar SetForegroundWindow: {}",
        "wscript_activation_error": "Erro durante a ativação via WScript.Shell: {}",
        "window_not_found": "Janela '{}' não encontrada.",
        "window_interaction_error": "Erro ao interagir com a janela '{}': {}",
        "window_activation_failed": "Falha ao confirmar ativação. Janela ativa: {} (HWND: {})",
        "trying_setforegroundwindow": "Tentando ativar via SetForegroundWindow...",
        "window_activated_setforegroundwindow": "Janela '{}' ativada via SetForegroundWindow.",
        "closing_main_for_calibration": "Fechando janela principal para calibração...",
        "any_cript_selected": "Modo Any: selecionando próxima cripta sem validação de imagem...",
        "errors_was_detected": "Erros detectados"
    },
    "en": {
        "any_cript_selected": "Any mode: selecting next crypt without image validation...",
        "closing_main": "Closing main window...",
        "starting_script": "Starting script...\n",
        "selecting_all_in": "Selecting all in: {}",
        "window_activated": "Window '{}' successfully activated.",
        "window_activation_failed": "Failed to confirm activation. Active window: {} (HWND: {})",
        "trying_setforegroundwindow": "Trying to activate via SetForegroundWindow...",
        "window_activated_setforegroundwindow": "Window '{}' activated via SetForegroundWindow.",
        "window_not_found": "Window '{}' not found.",
        "window_size_error": "Error capturing window size: {}",
        "setforeground_failed": "SetForegroundWindow also failed.",
        "setforeground_error": "Error using SetForegroundWindow: {}",
        "wscript_activation_error": "Error during WScript.Shell activation: {}",
        "window_not_found": "Window '{}' not found.",
        "window_interaction_error": "Error interacting with window '{}': {}",
        "trying_activate_window": "Trying to activate window: {}",
        "closing_main_for_calibration": "Closing main window for calibration...",
        "image_load_error": "Error loading image {}: {}",
        "no_directory_loaded": "No directory loaded to select all.",
        "script_finished": "--- Script Finished ---",
        "cripting_interrupted": "Cripting interrupted",
        "window_maximizing": "Maximizing window '{}'...",
        "window_activating_wscript": "Trying to activate window '{}' via WScript.Shell...",
        "error_serch_cript": "Error in search cript",
        "error_in_cript": "Error in cript",
        "errors_was_detected": "Errors detected",
        "error_in_speedup_march": "Error in Speedy March",
        "explored_cripts": "Explored cripts",
        "window_found": "Window '{}' found (HWND: {}).",
        "window_minimized": "Window '{}' is minimized. Restoring...",
        "cript_speedup": "Speedy March",
        "Invading_crypt": "Invading the crypt",
        "store_screen_close": "Store screen close",
        "terminating_process": "Terminating cripting process...",
        "child_process_terminated": "Child process terminated.",
        "child_process_error": "Error terminating child process: {}",
        "destroying_status": "Destroying status window...",
        "destroying_main": "Destroying main window...",
        "exiting_script": "Exiting launcher script...",
        "closing_status": "Closing status window...",
        "waiting_acceleration_screen_close": "Waiting to the acceleration screen close",
        "trying_terminate_process": "Trying to terminate cripting process...",
        "sending_kill": "Sending kill() to the process...",
        "process_terminated": "Process terminated via kill() and wait().",
        "process_timeout": "Process did not terminate after kill() and wait() (TimeoutExpired). This is unexpected.",
        "kill_error": "Error trying to kill the process: {}",
        "process_ref_cleared": "Process reference cleared.",
        "status_update_error": "Could not update status window (probably already destroyed).",
        "destroying_status_window": "Destroying status window.",
        "status_close_complete": "Status window closing completed.",
        "config_saved_debug": "Saving to config: search_cript = {}",
        "dir_not_found": "Warning: Directory not found: {}",
        "rel_path_error": "Error generating relative path for: {}",
        "selected_items": "Selected: {}",
        "cripta_encontrada": "Crypt found",
        "error_in_speedy_march": "Error in Speedy March",
        "troops_screen_close": "Troops screen close",
        "wrong_windows_opened": "There were wrong windows opened",
        "explore_button_not_found": "Explore button not found, try other position",
        "explorer_button_after_store_not_found": "Explorer button after store screen not found, search next point of click",
        "config_load_error": "Error loading initial configuration: {}",
        "selected_paths": "Selected:",
        "process_killed": "Process terminated via kill() and wait().",
        "process_not_killed_timeout": "Process did not terminate after kill() and wait() (TimeoutExpired). This is unexpected.",
        "error_killing_process": "Error trying to kill process: {}",
        "process_interrupted_by_user": "--- Process Interrupted by User ---",
        "esc_pressed_interrupting": "Esc key pressed. Interrupting...",
        "time_is_over": "Time is over!"
    }
}

# Mensagens de calibração
CALIBRATION = {
    "pt": {
        "script_not_found": "Script de calibração não encontrado:\n{}",
        "calibration_error": "Erro ao executar o script de calibração:\n{}",
        "closing_for_calibration": "Fechando janela principal para calibração..."
    },
    "en": {
        "script_not_found": "Calibration script not found:\n{}",
        "calibration_error": "Error executing calibration script:\n{}",
        "closing_for_calibration": "Closing main window for calibration..."
    }
}

# Mensagens para ativação de janela
WINDOW = {
    "pt": {
        "window_found": "Janela '{}' encontrada (HWND: {}).",
        "window_minimized": "Janela '{}' está minimizada. Restaurando...",
        "maximizing": "Maximizando a janela '{}'...",
        "activating": "Tentando ativar a janela '{}' via WScript.Shell...",
        "activation_success": "Janela '{}' ativada com sucesso.",
        "activation_fail": "Falha ao confirmar ativação. Janela ativa: {} (HWND: {})",
        "trying_setforeground": "Tentando ativar via SetForegroundWindow...",
        "setforeground_success": "Janela '{}' ativada via SetForegroundWindow.",
        "setforeground_fail": "SetForegroundWindow também falhou.",
        "setforeground_error": "Erro ao usar SetForegroundWindow: {}",
        "wscript_error": "Erro durante a ativação via WScript.Shell: {}",
        "window_not_found": "Janela '{}' não encontrada.",
        "window_interaction_error": "Erro ao interagir com a janela '{}': {}"
    },
    "en": {
        "window_found": "Window '{}' found (HWND: {}).",
        "window_minimized": "Window '{}' is minimized. Restoring...",
        "maximizing": "Maximizing window '{}'...",
        "activating": "Trying to activate window '{}' via WScript.Shell...",
        "activation_success": "Window '{}' successfully activated.",
        "activation_fail": "Failed to confirm activation. Active window: {} (HWND: {})",
        "trying_setforeground": "Trying to activate via SetForegroundWindow...",
        "setforeground_success": "Window '{}' activated via SetForegroundWindow.",
        "setforeground_fail": "SetForegroundWindow also failed.",
        "setforeground_error": "Error using SetForegroundWindow: {}",
        "wscript_error": "Error during activation via WScript.Shell: {}",
        "window_not_found": "Window '{}' not found.",
        "window_interaction_error": "Error interacting with window '{}': {}"
    }
}

# Função para obter texto traduzido
def get_text(dictionary, key, lang="pt"):
    """Obtém o texto traduzido do dicionário para o idioma especificado."""
    if lang in dictionary and key in dictionary[lang]:
        return dictionary[lang][key]
    return key  # Retorna a chave como fallback se não encontrar tradução
